# Generated by Django 4.1.1 on 2022-09-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribemail',
            name='link',
            field=models.URLField(default='none'),
        ),
    ]
