# Generated by Django 4.1.1 on 2022-09-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subscribemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribemail',
            name='text',
            field=models.TextField(),
        ),
    ]
